import { useNavigate } from 'react-router-dom';
import { Button } from 'react-md';
import { useEffect, useState } from 'react';
import { DocumentData } from 'firebase/firestore';

import ProductTable from '../../components/product-table/product-table.component';
import { Polish } from '../../store/product/product.types';
import NewProductButtons from '../../components/new-product-buttons/new-product-buttons';

import { ProductContainer } from './new-product.styles';
import { addNewItem } from '../../utils/firestore/firestore.utils';

const NewProduct = () => {
  const emptyProduct: Polish = {
    id: '',
    brand: '',
    name: '',
    color: '',
    effects: [],
    multichrome: [],
    imageUrls: [],
    other: [],
    volume: 0,
  };

  const navigate = useNavigate();
  const [product, setProduct] = useState(emptyProduct);

  const mutation = addNewItem('products');

  const setProductFromChild = (product: Polish | DocumentData) => {
    setProduct(product as Polish);
  };

  const saveClickedFromChild = () => {
    mutation.mutate(product);
  };

  const cancelClickedFromChild = () => {
    navigate('/products');
  };
  
  useEffect(() => {
    if (mutation.isSuccess) {
      navigate(`/products/${mutation.data?.id}`);
    }
  }, [mutation]);

  return (
    <ProductContainer>
      <Button themeType="contained" onClick={() => navigate('/products')}>
        Back to product list
      </Button>
      <NewProductButtons
        editable={true}
        seteditable={()=>{}}
        onSaveClicked={saveClickedFromChild}
        onCancelClicked={cancelClickedFromChild}
        mutation={mutation}
      />
      <ProductTable productId={'This will be generated by Firestore'} product={product} editable={true} setproduct={setProductFromChild} />
    </ProductContainer>
  );
};

export default NewProduct;

// új productnál
