import { useNavigate } from 'react-router-dom';
import { Button } from 'react-md';
import { useEffect, useState } from 'react';
import { DocumentData } from 'firebase/firestore';

import BottleTable from '../../components/bottle-table/bottle-table.component';
import { PolishBottle } from '../../store/product/product.types';
import NewBottleButtons from '../../components/new-bottle-buttons/new-bottle-buttons';

import { BottleContainer } from './new-bottle.styles';
import { addNewItem } from '../../utils/firestore/firestore.utils';

const NewBottle = () => {
  const emptyBottle: PolishBottle = {
    productId: '',
    userId: '',
    locationUserId: '',
    fullPercentage: 0,
    photoUrl: '',
  };

  const navigate = useNavigate();
  const mutation = addNewItem('bottles');
  const [bottle, setBottle] = useState(emptyBottle);

  const setBottleFromChild = (bottle: PolishBottle | DocumentData) => {
    setBottle(bottle as PolishBottle);
  };
  
  const saveClickedFromChild = () => {
    mutation && mutation.mutate(bottle);
  };

  const cancelClickedFromChild = () => {
    navigate('/bottles');
  };

  useEffect(() => {
    if (mutation.isSuccess) {
      navigate(`/bottles/${mutation.data?.id}`);
    }
  }, [mutation]);

  return (
    <BottleContainer>
      <Button themeType="contained" onClick={() => navigate('/bottles')}>
        Back to bottle list
      </Button>
      <NewBottleButtons
        editable={true}
        seteditable={()=>{}}
        onSaveClicked={saveClickedFromChild}
        onCancelClicked={cancelClickedFromChild}
        mutation={mutation}
      />
      <BottleTable bottleId={'This will be generated by Firestore'} bottle={bottle} editable={true} setbottle={setBottleFromChild} />
    </BottleContainer>
  );
};

export default NewBottle;
